version: "3.9"

services:

  db:
    image: postgres:16
    container_name: postgres-db

    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: flask-backend

    ports:
      - "5000:5000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/productdb

    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  postgres_data:
